# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - trainticketreservation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: frontend

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json


      - name: Install dependencies and build
        run: |
          npm install
          npm run build


      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: frontend/dist


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read


    steps:

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-app


      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5BE135736A844CFDAA802BAAEAADE239 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2E81BFBE58CA478F9B0D1F16A2418D55 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C6E3A0F91C184D898403C09AFA64BD14 }}


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'trainticketreservation'
          slot-name: 'Production'
          package: .
          